/*
 * Final Project: Library Management System Database
 * 
 * This schema defines a comprehensive library database with the following entities:
 * - Books: Catalog with ISBN, titles, copies, and shelf locations
 * - Authors: Author information with support for multiple authors per book
 * - Categories: Book classification system
 * - Publishers: Publishing house details and contact information
 * - Members: Library patron records with membership status tracking
 * - Staff: Employee information and position details
 * - Borrowing: Transaction records for book checkouts and returns
 * - Fines: Overdue fine management and payment tracking
 * 
 * Features:
 * - Many-to-many relationship between books and authors (book_authors junction table)
 * - Foreign key constraints with CASCADE operations for referential integrity
 * - Status tracking for memberships, staff, borrowing records, and fines
 * - Automatic inventory management through copies_total and copies_available fields
 * 
 * Character set: UTF8MB3
 * Generated by: MySQL Workbench Forward Engineering
 */

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema librarydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `librarydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `librarydb` ;


CREATE TABLE IF NOT EXISTS `librarydb`.`author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `biography` VARCHAR(450) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `author_id_UNIQUE` (`author_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `librarydb`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE,
  UNIQUE INDEX `category_name_UNIQUE` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `librarydb`.`publishers` (
  `publisher_id` INT NOT NULL AUTO_INCREMENT,
  `publisher_name` VARCHAR(150) NOT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`publisher_id`),
  UNIQUE INDEX `publisher_id_UNIQUE` (`publisher_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `librarydb`.`books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(13) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `publisher_id` INT NULL DEFAULT NULL,
  `publication_year` INT NULL DEFAULT NULL,
  `copies_total` INT NOT NULL,
  `copies_available` INT NOT NULL,
  `shelf_location` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE,
  INDEX `fk_category_id_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_publisher_id_idx` (`publisher_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `librarydb`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publisher_id`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `librarydb`.`publishers` (`publisher_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 109
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `librarydb`.`book_authors` (
  `book_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `author_id`),
  INDEX `fk_author_id_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_authors_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `librarydb`.`author` (`author_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_book_authors_book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `librarydb`.`books` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `librarydb`.`members` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(200) NOT NULL,
  `membership_date` DATETIME NOT NULL,
  `membership_status` ENUM('Active', 'Inactive', 'Suspended') NULL DEFAULT NULL,
  PRIMARY KEY (`member_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `librarydb`.`staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `hire_date` DATETIME NOT NULL,
  `status` ENUM('Active', 'Inactive') NULL DEFAULT NULL,
  PRIMARY KEY (`staff_id`),
  UNIQUE INDEX `staff_id_UNIQUE` (`staff_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `librarydb`.`borrowing` (
  `borrowing_id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NULL DEFAULT NULL,
  `member_id` INT NULL DEFAULT NULL,
  `staff_id` INT NULL DEFAULT NULL,
  `borrow_date` DATETIME NOT NULL,
  `return_date` DATETIME NULL DEFAULT NULL,
  `status` ENUM('Borrowed', 'Returned', 'Overdue') NULL DEFAULT NULL,
  `due_date` DATETIME NOT NULL,
  PRIMARY KEY (`borrowing_id`),
  UNIQUE INDEX `borrowing_id_UNIQUE` (`borrowing_id` ASC) VISIBLE,
  INDEX `fk_book_id_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_member_id_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_staff_id_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `librarydb`.`books` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `librarydb`.`members` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `librarydb`.`staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `librarydb`.`fines` (
  `fine_id` INT NOT NULL AUTO_INCREMENT,
  `borrowing_id` INT NULL DEFAULT NULL,
  `fine_amount` DECIMAL(10,2) NOT NULL,
  `fine_date` DATETIME NOT NULL,
  `payment_status` ENUM('Unpaid', 'Paid', 'Waived') NULL DEFAULT NULL,
  `payment_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`fine_id`),
  UNIQUE INDEX `fine_id_UNIQUE` (`fine_id` ASC) VISIBLE,
  INDEX `fk_borrowing_id_idx` (`borrowing_id` ASC) VISIBLE,
  CONSTRAINT `fk_borrowing_id`
    FOREIGN KEY (`borrowing_id`)
    REFERENCES `librarydb`.`borrowing` (`borrowing_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;